
#
# Non-optional:
#

# Uncomment the line for your OS
OS=linux

# Linux only: Location of Linux sources?
LINUXSRC= /usr/src/linux-3.12.9-1-ARCH

#
# Optional:
#

# Edit this if your gcc cannot be found at the usual location
#CC=gcc-4.0

# Where to install
prefix=/usr/local

# Set to "y" to build MT versions of sendd and cgatool
USE_THREADS=n

# Enable to create and use static libraries for internal build
CREATE_ARCHIVE=y

# Enable to create shared libraries for internal build. 
CREATE_SHARED=n

# Set to y for statically linked binaries (must also set CREATE_ARCHIVE=y)
# If 'n', binaries will be linked against dynamic internal libraries.
# You will need to either put these libraries somewhere like /usr/lib,
# or set your runtime linking path. 'y' is recommended here.
STATIC=y

# Set to y to enable console on sendd and cgatool (libreadline recommended)
USE_CONSOLE=y

# Enable for debugging
DEBUG_POLICY= DEBUG
#DEBUG_POLICY= NO_DEBUG

# enable for timestamp output on some crypto operations
LOG_TIMESTAMP=n

#
# Chances are you won't want to touch anything below this point.
#
USE_READLINE=y
ETCINIT= /etc/init.d

# Only works ok on linux
LOG_BACKTRACE=n

PREFIXLIB= $(prefix)/lib
PREFIXINC= $(prefix)/include
PREFIXSBIN= $(prefix)/sbin

SND_VERSION= 0.4
SND_VERSION_DISTNAME= sendd$(SND_VERSION)
SND_VERSION_STR= "SEND Daemon version $(SND_VERSION)"
SND_NFQ_NUM= 58
